### ISSUE TITLE
Replace dependency on OpenAI function calling with Nexus Raven v2

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/digdir-assistants#10]
### Description

Nexus Raven can function as a drop-in replacement for OpenAI function calling. In our case, we have used function calling functionality for structured data extraction, but this is not supported natively on any open source LLMs. By post-processing open source LLM output with the Nexus Raven model, we can extract structured data as before, theoretically from any model.

```[tasklist]
### Tasks
- [ ] Extract existing function call structure from `instructor` patched prompts
- [ ] Test structured data extraction manually to verify robustness in handling of data input (enums especially)
- [ ] Evaluate performance of quantized models (significantly affects hosting options and cost)
```
