### ISSUE TITLE
Add incremental update job for extracting search phrases from updates docs

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/digdir-assistants#3]
### Description

Updating our search phrase index in batch mode takes too long and costs too much. Instead, we should be able to store a checksum and only update the index when content has actually changed.

Add this job to the list of scheduled jobs, preferably to be executed when `altinn-studio-docs/master` is updated.

```[tasklist]
### Tasks
- [x] Store `checksum`, `updated_at` in `altinn-studio-docs` collection when scraping source documents
- [x] Store checksum in `altinn-studio-docs-search-phrases` when generating search phrases
- [x] Add checksum check to avoid regenerating search phrases for unchanged content
```

**Comment by bdb-dd** [comment]
Implementation is complete, but we need a good (reliable, configurable, introspectible) scheduled task runtime with UI.

**Comment by bdb-dd** [comment]
Moving task scheduler to a separate issue.
