### ISSUE TITLE
Add support for channel specific prompt text

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/digdir-assistants#31]
### Description

In order to better support users in product specific Slack channels in the Altinn workspace, we should add support for channel specific prompt instructions.

This configuration should be stored in the DB and adminstrated through the Admin web UI.

```[tasklist]
### Tasks
- [x] Add config for custom query relaxation prompt
- [x] Add config for custom rag prompt
- [x] Add complete prompt to db, admin ui
```

**Comment by bdb-dd** [comment]
Deployed to production.
