### ISSUE TITLE
Upgrade typesense to v26 and activate new features

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/digdir-assistants#72]
### Description

With v26, Typesense has changed their versioning scheme to better communicate that the API is stable and has been production ready [for a few years](https://github.com/typesense/typesense/releases/tag/v26.0).

```[tasklist]
### Features in this release that we may benefit from:
- [ ] Image Search
- [x] Analytics (null hits tracking, doc level hit tracking)
- [ ] Sorting based on Filter Score
- [x] Stemming
- [ ] Prefix filtering
- [ ] Stop words
- [ ] Curate / Override by tags
```

```[tasklist]
### Tasks
- [x] Setup new cluster instance (blue/green)
- [x] Migrate existing collections from current cluster
- [x] Re-execute historical search queries and compare search results
- [x] Deploy to production
- [x] Run crawler to confirm successful updates
```

```[tasklist]
### Tasks
```
